name: Test Workflow
on:
  push:
    branches:
      - "test-0"
    paths:
      - services/**
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Test Step
        run: echo Testing, it was pushed to ${{ github.ref }}
